### ISSUE TITLE
按照功能拆分models、views、forms文件为多个文件

### ISSUE THREAD

**Issue by Ma233** [Junnplus/UIAMS#8]
分别置入 models、controller、forms 文件夹。
views文件的拆分参考 blueprint 。
validator 放到 controller 文件夹下，或者新建文件夹 lib 。

**Comment by Ma233** [comment]
顺便一说 `view.py~` 是什么鬼 =_=

**Comment by Junnplus** [comment]
不是说好了不写蓝本嘛

**Comment by Junnplus** [comment]
views.py~我也不知道，，，2333

**Comment by Ma233** [comment]
写一写又不会怀孕，几行代码的事儿能让你的工程更易于维护。

**Comment by Ma233** [comment]
http://flask.pocoo.org/docs/0.10/blueprints/

**Comment by Junnplus** [comment]
嚓，，，之前都问你要不要蓝本，，，

**Comment by Ma233** [comment]
@Junnplus 
代码没有满意的一天，要时刻记得修改、重构嘛。我之前那么说是因为你还没有写出来。

**Comment by Junnplus** [comment]
2333,重构，，，还要改数据库，，，5555
